export const keywords = [
  'voltfinder',
  'elektromos autó',
  'töltő',
  'töltőállomás',
  'töltőpont',
  'töltőhely',
  'töltőállomás kereső',
  'töltőpont kereső',
  'töltőhely kereső',
  'töltőállomás kereső',
  'térkép',
  'ionity',
  'mobility',
  'mvm',
  'lidl',
  'shell',
  'recharge',
  'mol',
  'plugee',
  'omw',
  'e-motion',
  'eon',
  'tea',
  'greentetik',
  'ac',
  'dc',
  'villámtöltő',
  'bmw',
  'charging',
  'bmw charging',
  'villanyautó',
  'ev',
  'ev charger',
  'elektromos autó töltés',
  'ingyenes töltőpont',
  'gyorstöltő',
  'ultragyors töltő',
  'elektromos autó térkép',
  'nyilvános töltőpontok',
  'EV töltés',
  'töltőállomás árak',
  'elektromos jármű töltő',
  'EV térkép',
  'elektromos autó töltőállomások',
  'hálózati töltő',
  'e-autó',
  'okos töltő',
  'otthoni töltő',
  'CCS töltő',
  'CHAdeMO',
  'elektromos autó infrastruktúra',
  'zöld autózás',
  'CO2 semleges közlekedés',
  'fenntartható autózás',
  'töltőállomás elérhetőség',
  'villanyautó töltési díjak',
];
